require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SquadsController do

  def mock_squad(stubs={})
    @mock_squad ||= mock_model(Squad, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all squads as @squads" do
      Squad.stub(:all) { [mock_squad] }
      get :index
      assigns(:squads).should eq([mock_squad])
    end
  end

  describe "GET show" do
    it "assigns the requested squad as @squad" do
      Squad.stub(:find).with("37") { mock_squad }
      get :show, :id => "37"
      assigns(:squad).should be(mock_squad)
    end
  end

  describe "GET new" do
    it "assigns a new squad as @squad" do
      Squad.stub(:new) { mock_squad }
      get :new
      assigns(:squad).should be(mock_squad)
    end
  end

  describe "GET edit" do
    it "assigns the requested squad as @squad" do
      Squad.stub(:find).with("37") { mock_squad }
      get :edit, :id => "37"
      assigns(:squad).should be(mock_squad)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created squad as @squad" do
        Squad.stub(:new).with({'these' => 'params'}) { mock_squad(:save => true) }
        post :create, :squad => {'these' => 'params'}
        assigns(:squad).should be(mock_squad)
      end

      it "redirects to the created squad" do
        Squad.stub(:new) { mock_squad(:save => true) }
        post :create, :squad => {}
        response.should redirect_to(squad_url(mock_squad))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved squad as @squad" do
        Squad.stub(:new).with({'these' => 'params'}) { mock_squad(:save => false) }
        post :create, :squad => {'these' => 'params'}
        assigns(:squad).should be(mock_squad)
      end

      it "re-renders the 'new' template" do
        Squad.stub(:new) { mock_squad(:save => false) }
        post :create, :squad => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested squad" do
        Squad.stub(:find).with("37") { mock_squad }
        mock_squad.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :squad => {'these' => 'params'}
      end

      it "assigns the requested squad as @squad" do
        Squad.stub(:find) { mock_squad(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:squad).should be(mock_squad)
      end

      it "redirects to the squad" do
        Squad.stub(:find) { mock_squad(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(squad_url(mock_squad))
      end
    end

    describe "with invalid params" do
      it "assigns the squad as @squad" do
        Squad.stub(:find) { mock_squad(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:squad).should be(mock_squad)
      end

      it "re-renders the 'edit' template" do
        Squad.stub(:find) { mock_squad(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested squad" do
      Squad.stub(:find).with("37") { mock_squad }
      mock_squad.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the squads list" do
      Squad.stub(:find) { mock_squad }
      delete :destroy, :id => "1"
      response.should redirect_to(squads_url)
    end
  end

end
